package ua.com.alevel;

public class Main {
    public static void main(String[] args) {
        System.out.println("Demonstration how MathSet works");
        System.out.println("Add next numbers:");
        MathSet mathSet1 = new MathSet();
        MathSet mathSet2 = new MathSet();
        MathSet mathSet3 = new MathSet();
        MathSet cut = new MathSet();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);

        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("join mathsets:");
        mathSet1.join(mathSet2);
        System.out.println("mathset1 join mathset2: " + mathSet1);
        mathSet1.join(mathSet3);
        System.out.println("mathset1 join mathset3: " + mathSet1);
        mathSet1.join(mathSet2, mathSet3);
        System.out.println("mathset1 join mathset2 join mathset3: " + mathSet1);
        System.out.println();
        System.out.println("intersection mathsets: ");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        mathSet1.intersection(mathSet2);
        System.out.println("mathset1 intersection mathset2: " + mathSet1);
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        mathSet1.intersection(mathSet2, mathSet3);
        System.out.println("mathset1 intersection mathset2,mathSet3: " + mathSet1);
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        System.out.println();
        System.out.println("descending sort: ");
        mathSet1.sortDesc();
        mathSet2.sortDesc();
        mathSet3.sortDesc();
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("ascending sort: ");
        mathSet1.sortAsc();
        mathSet2.sortAsc();
        mathSet3.sortAsc();
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("descending sort from index (For example 2 to 4): ");
        mathSet1.sortDesc(2, 4);
        mathSet2.sortDesc(2, 4);
        mathSet3.sortDesc(2, 4);
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("ascending sort from index (For example 2 to 4): ");
        mathSet1.sortAsc(2, 4);
        mathSet2.sortAsc(2, 4);
        mathSet3.sortAsc(2, 4);
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("descending sort from value:");
        System.out.println("mathset1 from value 3:");
        System.out.println("mathset1 from value 5:");
        System.out.println("mathset1 from value 7:");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        mathSet1.sortDesc(3);
        mathSet2.sortDesc(5);
        mathSet3.sortDesc(7);
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("ascending sort from value:");
        System.out.println("mathset1 from value 3:");
        System.out.println("mathset1 from value 5:");
        System.out.println("mathset1 from value 7:");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        mathSet1.sortAsc(3);
        mathSet2.sortAsc(5);
        mathSet3.sortAsc(7);
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
        System.out.println();
        System.out.println("get Number from index: ");
        System.out.println("mathset1 from index 2:");
        System.out.println("mathset2 from index 3:");
        System.out.println("mathset3 from index 4:");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        System.out.println(mathSet1.get(2));
        System.out.println(mathSet2.get(3));
        System.out.println(mathSet3.get(4));
        System.out.println();
        System.out.println("get max: ");
        System.out.println("mathset1 max: " + mathSet1.getMax());
        System.out.println("mathset2 max: " + mathSet2.getMax());
        System.out.println("mathset3 max: " + mathSet3.getMax());
        System.out.println();
        System.out.println("get min: ");
        System.out.println("mathset1 min: " + mathSet1.getMin());
        System.out.println("mathset2 min: " + mathSet2.getMin());
        System.out.println("mathset3 min: " + mathSet3.getMin());
        System.out.println();
        System.out.println("get average: ");
        System.out.println("mathset1 average: " + mathSet1.getAverage());
        System.out.println("mathset2 average: " + mathSet2.getAverage());
        System.out.println("mathset3 average: " + mathSet3.getAverage());
        System.out.println();
        System.out.println("get median: ");
        System.out.println("mathset1 median: " + mathSet1.getMedian());
        System.out.println("mathset2 median: " + mathSet2.getMedian());
        System.out.println("mathset3 median: " + mathSet3.getMedian());
        System.out.println();
        System.out.println("to array: ");
        Number[] ms1;
        Number[] ms2;
        Number[] ms3;
        ms1 = mathSet1.toArray();
        ms2 = mathSet2.toArray();
        ms3 = mathSet3.toArray();
        System.out.println("Mathset1 to array: ");
        for (int i = 0; i < ms1.length; i++) {
            System.out.println(ms1[i]);
        }
        System.out.println("Mathset2 to array: ");
        for (int i = 0; i < ms2.length; i++) {
            System.out.println(ms2[i]);
        }
        System.out.println("Mathset3 to array: ");
        for (int i = 0; i < ms3.length; i++) {
            System.out.println(ms3[i]);
        }
        System.out.println();
        System.out.println("to array from index: (For example from 2 to 4)");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        mathSet1.add(1, 20, 3, 40, 5);
        mathSet2.add(3, 40, 5, 60, 7);
        mathSet3.add(5, 60, 7, 80, 9);
        ms1 = mathSet1.toArray(2, 4);
        ms2 = mathSet2.toArray(2, 4);
        ms3 = mathSet3.toArray(2, 4);
        System.out.println("Mathset1 to array from index to index: (For example from 2 to 4)");
        for (int i = 0; i < ms1.length; i++) {
            System.out.println(ms1[i]);
        }
        System.out.println("Mathset2 to array from index to index: (For example from 2 to 4) ");
        for (int i = 0; i < ms2.length; i++) {
            System.out.println(ms2[i]);
        }
        System.out.println("Mathset3 to array from index to index: (For example from 2 to 4) ");
        for (int i = 0; i < ms3.length; i++) {
            System.out.println(ms3[i]);
        }
        System.out.println();
        System.out.println("MathSet cut from index to index");
        System.out.println("cut from mathset1: ");
        cut = mathSet1.cut(2, 4);
        System.out.println(cut);
        System.out.println("cut from mathset2: ");
        cut = mathSet2.cut(2, 4);
        System.out.println(cut);
        System.out.println("cut from mathset3: ");
        cut = mathSet3.cut(2, 4);
        System.out.println(cut);
        System.out.println();
        System.out.println("clear:");
        mathSet1.clear();
        mathSet2.clear();
        mathSet3.clear();
        System.out.println(mathSet1);
        System.out.println(mathSet2);
        System.out.println(mathSet3);
    }
}
